# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d3c4f3a840bc912301acdd533bd5b2d774df5f95025338461922554d7f4454b1b44dec86a093fdd7916b34e2978c6fa0ab65e5364f5b8d3260409f8f3b983dd

test:
  secret_key_base: 2524d400e15bf22828b18720b3560a97ab1a44a6da0adbeeede77ffc2698165049db5380fe0931b927a2b7fb3368ddb620c471b79d4e2cacb7ba1f49014c8a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
